# Includes enviornment specific properties.
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/oars
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 2
        max-page-size: 5
