# Includes enviornment specific properties.
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_boilerplate
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 2
        max-page-size: 5
